name: vcs_portal
description: A Flutter login/register app connected to Flask and MySQL.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl : ^0.18.1
  chess: ^0.8.1
  provider: ^6.1.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/
    - assets/background.png
    - assets/images/vc_drone_view.png
    - assets/images/VC_icon.png
    - assets/images/games_icon.png
    - assets/stockfish/
    - assets/images/
  uses-material-design: true